CREATE TABLE vehicles (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vehicle_category    VARCHAR(20)  NOT NULL,
    usage_measure       VARCHAR(10)  NOT NULL,
    heavy_subtype       VARCHAR(100),
    license_plate       VARCHAR(20),
    make                VARCHAR(100) NOT NULL,
    model               VARCHAR(100) NOT NULL,
    year                INT          NOT NULL,
    vin                 VARCHAR(17),
    color               VARCHAR(50),
    status              VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    current_km          BIGINT,
    current_hours       BIGINT,
    acquisition_type    VARCHAR(10),
    acquisition_date    DATE,
    purchase_price      NUMERIC(12, 2),
    amortization_years  INT,
    monthly_fee         NUMERIC(12, 2),
    contract_end_date   DATE,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ
);
